on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.REPO_SECRET }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
