# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
      name: Build for Windows, Linux, and macOS
      runs-on: ${{ matrix.os }}
      
      strategy:
        matrix:
          go-version: [1.23]
          os: [ubuntu-latest, windows-latest, macos-latest]  # Target platforms
  
      steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Install dependencies
        run: go mod tidy
  
      - name: Build the project
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            GOOS=linux
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            GOOS=windows
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            GOOS=darwin
          fi

          GOARCH=amd64
          go build -o atcoder-testcase-runner-${GOOS}-${GOARCH}
        shell: bash
  
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: atcoder-testcase-runner-${{ matrix.os }}
          path: atcoder-testcase-runner-${{ matrix.os }}-amd64
