# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
      name: Build for Windows, Linux, and macOS
      runs-on: ${{ matrix.os }}
      
      strategy:
        matrix:
          go-version: [1.23]
          os: [ubuntu-latest, windows-latest, macos-latest]  # Target platforms
  
      steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Install dependencies
        run: go mod tidy
  
      - name: Build the project
        run: |
          GOOS=$(echo ${{ matrix.os }} | cut -d'-' -f1)
          GOARCH=amd64  # Adjust architecture if needed, e.g., for ARM
          go build -o myapp-${GOOS}-${GOARCH}
  
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.os }}
          path: myapp-${{ matrix.os }}-amd64
